# Localization

- p-hit = 0.6
- p-miss = 0.2

In [43]:
p_hit = 0.6
p_miss = 0.2

- probability of moving to the next cell = 0.8
- probability of staying in the same cell = 0.1
- probability of overshooting to the next cell = 0.1

In [44]:
p_next_cell = 0.8
p_stay = 0.1
p_overshoot = 0.1

Task 0: Define an array named world that represents the vehicle environment.
world = [‘tree’, ‘house’, ‘house’, ‘tree’, ‘tree’]

In [45]:
world = ['tree', 'house', 'house', 'tree', 'tree']

Task 1: Define a vector p (of size 1-by-n, where n is the number of discrete cell locations
in the environment) representing current belief for vehicle location (hint: in this case it is
initialised by a uniform distribution over the five cell locations). What is the value of p?

In [46]:
p_vec = [1 / len(world) for x in world]
p_vec

[0.2, 0.2, 0.2, 0.2, 0.2]

Task 2: Now the vehicle senses its environment, and observes a house. Update the belief
vector, by writing a function sense to which you pass on a measurement (’house’ or ’tree’), the current belief p, and it returns a new vector q which represents the updated belief after
the measurement (taking into account world, p-hit and p-miss). What is the value of updated
q?

In [47]:
def sense(measurement, current_belief):
    q = [0] * len(world)
    for i in range(len(world)):
        if world[i] == measurement:
            q[i] = current_belief[i] * p_hit
        else:
            q[i] = current_belief[i] * p_miss
    return q


q = sense('house', p_vec)
q

[0.04000000000000001, 0.12, 0.12, 0.04000000000000001, 0.04000000000000001]

Task 3: Does q represent a valid probability distribution? If not, why? Update it such
that it represents a valid probability distribution and assign it to p. What is the value of p
now?

No it does not, since the sum of the probabilities is not 1

In [48]:
def normalize(q):
    p = [x / sum(q) for x in q]
    return p


p = normalize(q)
p

[0.1111111111111111,
 0.3333333333333332,
 0.3333333333333332,
 0.1111111111111111,
 0.1111111111111111]

Task 4: Update your code such that it can handle a measurement vector with an arbitrary
number of measurements. Now let’s begin with a vector p representing a uniform distribution,
and you get two measurements, first a ‘house’ and then a ‘tree’. What will be the new p after
incorporating these two measurements (hint: the program will essentially loop for the total
number of available measurements (two in this case), following the steps described in tasks 2
and 3 above). Whats the updated p?

In [49]:
def updated_sense(measurements, current_belief):
    new_p = []
    for measurement in measurements:
        new_p = sense(measurement, current_belief)

    return new_p


p = updated_sense(['house', 'tree'], p_vec)
p

[0.12, 0.04000000000000001, 0.04000000000000001, 0.12, 0.12]

Task 5: Your next task is to write a function move that takes a current belief, and returns
a new belief for one-cell, clockwise, motion command execution in the vehicle environment.
Begin with an initial belief of [0, 0, 1, 0, 0]. As described in the introduction, please keep
in mind that the vehicle under- and overshoots with probabilities of 0.1 and 0.1, respectively
and performs an exact motion to the next cell with probability 0.8. You can declare three
variables to represent these probabilities in your program. What is the updated p after one
step of motion?

In [50]:
def move(current_belief):
    p = [0] * len(world)
    for i in range(len(current_belief)):
        p[i] += current_belief[i] * p_stay
        p[(i + 1) % len(current_belief)] += current_belief[i] * p_next_cell
        p[(i + 2) % len(current_belief)] += current_belief[i] * p_overshoot
    return normalize(p)


p = move([0, 0, 1, 0, 0])
p

[0.0, 0.0, 0.1, 0.8, 0.1]

Task 6: Starting from initial distribution of [0, 0, 1, 0, 0], what is the p after two one-step
motions? And after 100 one-step motions?

In [51]:
p = [0, 0, 1, 0, 0]
for i in range(2):
    p = move(p)
print(p)
p_2 = [0, 0, 1, 0, 0]
for i in range(100):
    p_2 = move(p_2)
print(p_2)

[0.16, 0.01, 0.01, 0.16, 0.66]
[0.1999998875814723, 0.20000004294005663, 0.2000001389569422, 0.20000004294005663, 0.1999998875814723]


Task 7: If you start from a uniform-distribution initial belief, what is the updated belief
after one step of motion?

In [52]:
p = move(p_vec)
p

[0.19999999999999996,
 0.19999999999999998,
 0.19999999999999998,
 0.19999999999999998,
 0.19999999999999998]

Task 8: Start with a uniform prior distribution. The vehicle senses a house, moves one step,
senses a tree, and moves one step again. What will be the posterior distribution (updated
2
vector p)? Does it make sense in relation to the vehicle environment?

In [53]:
p = sense('house', p_vec)
p = move(p)
p = sense('tree', p)
p = move(p)
p

[0.2115789473684211,
 0.15157894736842106,
 0.08105263157894739,
 0.16842105263157892,
 0.38736842105263153]

Task 9: Again start with a uniform prior distribution. The vehicle now senses a tree,
moves one step, senses a tree again, moves one step, and senses a tree yet again, and moves
again one step. What is the posterior distribution now? Does it make sense?

In [54]:
p = sense('tree', p_vec)
p = move(p)
p = sense('tree', p)
p = move(p)
p = sense('tree', p)
p = move(p)
p

[0.2332175925925926,
 0.40771604938271605,
 0.18086419753086416,
 0.07561728395061727,
 0.1025848765432099]

In [55]:
#import numpy
import numpy as np

In [56]:
X = np.array([[0], [0]]) #state vector
P = np.array([[1000, 0], [0, 1000]]) # covariance matrix
U = np.array([[0], [0]]) # motion vector
R = np.array([[1]]) # measurement noise
I = np.identity(2) #identitiy matrix

F = np.array([[1, 1], [0, 1]]) #state transition

H = np.array([[1, 0]]) #measurement matrix

measurements = np.array([[1], [2], [3]])

for measurement in measurements:
    Y = measurement - H.dot(X)  #error
    S = H.dot(P).dot(H.T) + R
    K = P.dot(H.T).dot(np.linalg.inv(S))
    X = X + K.dot(Y)
    P = (I - K.dot(H)).dot(P)
    
    # Prediction
    X = F.dot(X) + U
    P = F.dot(P).dot(F.T)
    
    print("Updated X:\n",X)
    print("Updated P:\n",P)
    


Updated X:
 [[0.999001]
 [0.      ]]
Updated P:
 [[1000.999001 1000.      ]
 [1000.       1000.      ]]
Updated X:
 [[2.99800299]
 [0.999002  ]]
Updated P:
 [[4.99002494 2.99301795]
 [2.99301795 1.99501297]]
Updated X:
 [[3.99966644]
 [0.99999983]]
Updated P:
 [[2.33189042 0.99916761]
 [0.99916761 0.49950058]]
